#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4{1,0,15.12,3
#
tcpEchoCC3X00.xem4: package/cfg/tcpEchoCC3X00.xem4.mak

clean::
	-$(RM) package/cfg/tcpEchoCC3X00.xem4.mak
